// Realistic fake data for TaskFlow UI mockup

export const currentUser = {
  id: "usr_1",
  name: "Sarah Fletcher",
  email: "sarah@fletcherdesign.co",
  initials: "SF",
  businessName: "Fletcher Design Co.",
  timezone: "America/New_York",
};

export const clients = [
  {
    id: "cli_1",
    name: "Meridian Health Partners",
    contactName: "David Chen",
    email: "david@meridianhealth.com",
    phone: "(415) 555-0182",
    activeProjects: 2,
    outstandingInvoices: "$4,200.00",
    totalRevenue: "$28,750.00",
    status: "active" as const,
    defaultRate: 125,
    color: "#6366F1",
  },
  {
    id: "cli_2",
    name: "Luminance Coffee Roasters",
    contactName: "Priya Sharma",
    email: "priya@luminancecoffee.com",
    phone: "(503) 555-0219",
    activeProjects: 1,
    outstandingInvoices: "$0.00",
    totalRevenue: "$12,400.00",
    status: "active" as const,
    defaultRate: 110,
    color: "#EC4899",
  },
  {
    id: "cli_3",
    name: "Northstar Financial Group",
    contactName: "James Whitfield",
    email: "j.whitfield@northstarfg.com",
    phone: "(212) 555-0347",
    activeProjects: 1,
    outstandingInvoices: "$8,500.00",
    totalRevenue: "$52,300.00",
    status: "active" as const,
    defaultRate: 150,
    color: "#14B8A6",
  },
  {
    id: "cli_4",
    name: "Verde Landscape Architecture",
    contactName: "Maria Santos",
    email: "maria@verdelandscape.com",
    phone: "(310) 555-0456",
    activeProjects: 0,
    outstandingInvoices: "$1,800.00",
    totalRevenue: "$9,200.00",
    status: "active" as const,
    defaultRate: 100,
    color: "#F97316",
  },
  {
    id: "cli_5",
    name: "Atlas Education Initiative",
    contactName: "Robert Kimura",
    email: "rkimura@atlasedu.org",
    phone: "(617) 555-0593",
    activeProjects: 0,
    outstandingInvoices: "$0.00",
    totalRevenue: "$15,600.00",
    status: "archived" as const,
    defaultRate: 95,
    color: "#8B5CF6",
  },
];

export const projects = [
  {
    id: "prj_1",
    clientId: "cli_1",
    clientName: "Meridian Health Partners",
    name: "Patient Portal Redesign",
    status: "active" as const,
    billingType: "hourly" as const,
    hourlyRate: 125,
    budgetHours: 80,
    hoursTracked: 52.5,
    budgetAmount: 10000,
    amountTracked: 6562.5,
    deadline: "2026-04-15",
    taskCount: 18,
    overdueTaskCount: 2,
    color: "#6366F1",
  },
  {
    id: "prj_2",
    clientId: "cli_2",
    clientName: "Luminance Coffee Roasters",
    name: "E-Commerce Store Build",
    status: "active" as const,
    billingType: "fixed_price" as const,
    fixedPrice: 15000,
    budgetHours: 120,
    hoursTracked: 34,
    budgetAmount: 15000,
    amountTracked: 5100,
    deadline: "2026-05-01",
    taskCount: 24,
    overdueTaskCount: 0,
    color: "#EC4899",
  },
  {
    id: "prj_3",
    clientId: "cli_1",
    clientName: "Meridian Health Partners",
    name: "Brand Identity Refresh",
    status: "on_hold" as const,
    billingType: "hourly" as const,
    hourlyRate: 125,
    budgetHours: 40,
    hoursTracked: 12,
    budgetAmount: 5000,
    amountTracked: 1500,
    deadline: "2026-06-30",
    taskCount: 8,
    overdueTaskCount: 0,
    color: "#6366F1",
  },
  {
    id: "prj_4",
    clientId: "cli_3",
    clientName: "Northstar Financial Group",
    name: "Annual Report Design",
    status: "active" as const,
    billingType: "fixed_price" as const,
    fixedPrice: 8500,
    budgetHours: 60,
    hoursTracked: 48,
    budgetAmount: 8500,
    amountTracked: 6800,
    deadline: "2026-03-20",
    taskCount: 14,
    overdueTaskCount: 3,
    color: "#14B8A6",
  },
];

export type TaskStatus = "todo" | "in_progress" | "waiting_on_client" | "review" | "done";
export type TaskPriority = "low" | "medium" | "high" | "urgent";

export interface Task {
  id: string;
  projectId: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  dueDate: string | null;
  subtasks: { id: string; title: string; completed: boolean }[];
  attachments: number;
  timeLogged: string;
  timeMinutes: number;
}

export const tasks: Task[] = [
  // To Do
  {
    id: "tsk_1",
    projectId: "prj_1",
    title: "Design appointment scheduling modal",
    description: "Create mockups for the new appointment booking flow including date picker, provider selection, and confirmation screen.",
    status: "todo",
    priority: "high",
    dueDate: "2026-03-12",
    subtasks: [
      { id: "st_1", title: "Wireframe layout options", completed: false },
      { id: "st_2", title: "Design date picker component", completed: false },
      { id: "st_3", title: "Create provider card design", completed: false },
    ],
    attachments: 1,
    timeLogged: "0h",
    timeMinutes: 0,
  },
  {
    id: "tsk_2",
    projectId: "prj_1",
    title: "Write copy for onboarding flow",
    description: "Draft patient-friendly copy for each step of the new user onboarding experience.",
    status: "todo",
    priority: "medium",
    dueDate: "2026-03-18",
    subtasks: [],
    attachments: 0,
    timeLogged: "0h",
    timeMinutes: 0,
  },
  {
    id: "tsk_3",
    projectId: "prj_1",
    title: "Audit existing color contrast ratios",
    description: "Run WCAG 2.1 AA contrast checks on all current portal components and document failures.",
    status: "todo",
    priority: "low",
    dueDate: null,
    subtasks: [
      { id: "st_4", title: "Check navigation elements", completed: false },
      { id: "st_5", title: "Check form components", completed: false },
      { id: "st_6", title: "Check status indicators", completed: false },
      { id: "st_7", title: "Document results in spreadsheet", completed: false },
    ],
    attachments: 0,
    timeLogged: "0h",
    timeMinutes: 0,
  },
  // In Progress
  {
    id: "tsk_4",
    projectId: "prj_1",
    title: "Build responsive navigation prototype",
    description: "Develop a working prototype of the new sidebar navigation that collapses on mobile with hamburger menu.",
    status: "in_progress",
    priority: "high",
    dueDate: "2026-03-08",
    subtasks: [
      { id: "st_8", title: "Desktop sidebar layout", completed: true },
      { id: "st_9", title: "Mobile hamburger menu", completed: true },
      { id: "st_10", title: "Animation transitions", completed: false },
      { id: "st_11", title: "Accessibility testing", completed: false },
    ],
    attachments: 3,
    timeLogged: "6h 30m",
    timeMinutes: 390,
  },
  {
    id: "tsk_5",
    projectId: "prj_1",
    title: "Implement patient profile cards",
    description: "Create the patient profile card component showing avatar, name, DOB, and upcoming appointment.",
    status: "in_progress",
    priority: "medium",
    dueDate: "2026-03-10",
    subtasks: [
      { id: "st_12", title: "Card layout", completed: true },
      { id: "st_13", title: "Avatar component", completed: true },
      { id: "st_14", title: "Data display formatting", completed: false },
    ],
    attachments: 2,
    timeLogged: "3h 15m",
    timeMinutes: 195,
  },
  // Waiting on Client
  {
    id: "tsk_6",
    projectId: "prj_1",
    title: "Finalize logo placement and sizing",
    description: "Client needs to approve final logo specs for the portal header area.",
    status: "waiting_on_client",
    priority: "medium",
    dueDate: "2026-03-05",
    subtasks: [],
    attachments: 4,
    timeLogged: "1h 45m",
    timeMinutes: 105,
  },
  // Review
  {
    id: "tsk_7",
    projectId: "prj_1",
    title: "Dashboard wireframes — v2",
    description: "Updated dashboard wireframes incorporating client feedback on data visualization priorities.",
    status: "review",
    priority: "high",
    dueDate: "2026-03-06",
    subtasks: [
      { id: "st_15", title: "Revise stat card layout", completed: true },
      { id: "st_16", title: "Add appointment timeline", completed: true },
      { id: "st_17", title: "Include notification panel", completed: true },
    ],
    attachments: 5,
    timeLogged: "8h 20m",
    timeMinutes: 500,
  },
  {
    id: "tsk_8",
    projectId: "prj_1",
    title: "Mobile-responsive table design",
    description: "Table component that collapses to card view on small screens for patient records.",
    status: "review",
    priority: "medium",
    dueDate: "2026-03-09",
    subtasks: [
      { id: "st_18", title: "Desktop table layout", completed: true },
      { id: "st_19", title: "Mobile card view", completed: true },
    ],
    attachments: 1,
    timeLogged: "4h 10m",
    timeMinutes: 250,
  },
  // Done
  {
    id: "tsk_9",
    projectId: "prj_1",
    title: "Set up design system tokens",
    description: "Define color palette, typography scale, spacing, and border radius tokens for the patient portal.",
    status: "done",
    priority: "high",
    dueDate: "2026-02-28",
    subtasks: [
      { id: "st_20", title: "Color tokens", completed: true },
      { id: "st_21", title: "Typography scale", completed: true },
      { id: "st_22", title: "Spacing system", completed: true },
      { id: "st_23", title: "Border radius tokens", completed: true },
      { id: "st_24", title: "Shadow definitions", completed: true },
    ],
    attachments: 2,
    timeLogged: "5h 00m",
    timeMinutes: 300,
  },
  {
    id: "tsk_10",
    projectId: "prj_1",
    title: "Competitive analysis document",
    description: "Research and document UX patterns from 5 competing patient portal platforms.",
    status: "done",
    priority: "medium",
    dueDate: "2026-02-25",
    subtasks: [],
    attachments: 1,
    timeLogged: "3h 45m",
    timeMinutes: 225,
  },
];

export const dashboardStats = {
  activeProjects: 3,
  activeProjectsTrend: "+1 from last month",
  upcomingDeadlines: 4,
  nextDeadline: "Annual Report — Mar 20",
  hoursThisWeek: 32.5,
  hoursTrend: "+12% vs. last week",
  billableHours: 28.0,
  outstandingInvoices: "$14,500.00",
  invoiceCount: 3,
  invoiceTrend: "2 overdue",
};

export const recentActivity = [
  {
    id: "act_1",
    action: "Completed task",
    detail: "Set up design system tokens",
    project: "Patient Portal Redesign",
    time: "2 hours ago",
  },
  {
    id: "act_2",
    action: "Logged 2h 15m",
    detail: "Build responsive navigation prototype",
    project: "Patient Portal Redesign",
    time: "3 hours ago",
  },
  {
    id: "act_3",
    action: "Invoice sent",
    detail: "INV-041 to Northstar Financial Group",
    project: "Annual Report Design",
    time: "Yesterday",
  },
  {
    id: "act_4",
    action: "New task created",
    detail: "Design appointment scheduling modal",
    project: "Patient Portal Redesign",
    time: "Yesterday",
  },
  {
    id: "act_5",
    action: "Payment received",
    detail: "$4,800.00 from Luminance Coffee Roasters",
    project: "E-Commerce Store Build",
    time: "2 days ago",
  },
];

export const analyticsData = {
  revenueByMonth: [
    { month: "Sep", revenue: 8200, hours: 62 },
    { month: "Oct", revenue: 11400, hours: 84 },
    { month: "Nov", revenue: 9800, hours: 72 },
    { month: "Dec", revenue: 7600, hours: 56 },
    { month: "Jan", revenue: 12300, hours: 88 },
    { month: "Feb", revenue: 10500, hours: 76 },
  ],
  revenueByClient: [
    { name: "Northstar Financial", value: 52300, color: "#14B8A6" },
    { name: "Meridian Health", value: 28750, color: "#6366F1" },
    { name: "Atlas Education", value: 15600, color: "#8B5CF6" },
    { name: "Luminance Coffee", value: 12400, color: "#EC4899" },
    { name: "Verde Landscape", value: 9200, color: "#F97316" },
  ],
  hoursBreakdown: [
    { name: "Billable", value: 28, color: "#22C55E" },
    { name: "Non-billable", value: 4.5, color: "#9CA3AF" },
  ],
  projectBudgets: [
    { name: "Patient Portal", budget: 80, used: 52.5, percentage: 66 },
    { name: "E-Commerce Store", budget: 120, used: 34, percentage: 28 },
    { name: "Brand Identity", budget: 40, used: 12, percentage: 30 },
    { name: "Annual Report", budget: 60, used: 48, percentage: 80 },
  ],
  weeklyHours: [
    { day: "Mon", hours: 7.5 },
    { day: "Tue", hours: 8.0 },
    { day: "Wed", hours: 6.5 },
    { day: "Thu", hours: 5.5 },
    { day: "Fri", hours: 5.0 },
  ],
};

export const invoices = [
  {
    id: "inv_1",
    number: "INV-041",
    clientName: "Northstar Financial Group",
    amount: "$8,500.00",
    issuedDate: "Feb 15, 2026",
    dueDate: "Mar 17, 2026",
    status: "sent" as const,
  },
  {
    id: "inv_2",
    number: "INV-040",
    clientName: "Verde Landscape Architecture",
    amount: "$1,800.00",
    issuedDate: "Feb 1, 2026",
    dueDate: "Mar 3, 2026",
    status: "overdue" as const,
  },
  {
    id: "inv_3",
    number: "INV-039",
    clientName: "Meridian Health Partners",
    amount: "$4,200.00",
    issuedDate: "Jan 28, 2026",
    dueDate: "Feb 27, 2026",
    status: "partial" as const,
  },
  {
    id: "inv_4",
    number: "INV-038",
    clientName: "Luminance Coffee Roasters",
    amount: "$4,800.00",
    issuedDate: "Jan 15, 2026",
    dueDate: "Feb 14, 2026",
    status: "paid" as const,
  },
];

export const statusColors: Record<string, { bg: string; text: string; dot: string }> = {
  active: { bg: "bg-green-50", text: "text-green-700", dot: "bg-green-500" },
  on_hold: { bg: "bg-amber-50", text: "text-amber-700", dot: "bg-amber-500" },
  completed: { bg: "bg-blue-50", text: "text-blue-700", dot: "bg-blue-500" },
  cancelled: { bg: "bg-gray-50", text: "text-gray-500", dot: "bg-gray-400" },
  todo: { bg: "bg-gray-50", text: "text-gray-600", dot: "bg-gray-400" },
  in_progress: { bg: "bg-blue-50", text: "text-blue-700", dot: "bg-blue-500" },
  waiting_on_client: { bg: "bg-amber-50", text: "text-amber-700", dot: "bg-amber-500" },
  review: { bg: "bg-violet-50", text: "text-violet-700", dot: "bg-violet-500" },
  done: { bg: "bg-green-50", text: "text-green-700", dot: "bg-green-500" },
  draft: { bg: "bg-gray-50", text: "text-gray-600", dot: "bg-gray-400" },
  sent: { bg: "bg-blue-50", text: "text-blue-700", dot: "bg-blue-500" },
  overdue: { bg: "bg-red-50", text: "text-red-700", dot: "bg-red-500" },
  partial: { bg: "bg-amber-50", text: "text-amber-700", dot: "bg-amber-500" },
  paid: { bg: "bg-green-50", text: "text-green-700", dot: "bg-green-500" },
  archived: { bg: "bg-gray-50", text: "text-gray-500", dot: "bg-gray-400" },
};

export const priorityColors: Record<string, { bg: string; text: string; border: string; label: string }> = {
  urgent: { bg: "bg-red-50", text: "text-red-700", border: "border-red-500", label: "Urgent" },
  high: { bg: "bg-orange-50", text: "text-orange-700", border: "border-orange-500", label: "High" },
  medium: { bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-500", label: "Medium" },
  low: { bg: "bg-gray-100", text: "text-gray-600", border: "border-gray-400", label: "Low" },
};

export const statusLabels: Record<string, string> = {
  active: "Active",
  on_hold: "On Hold",
  completed: "Completed",
  cancelled: "Cancelled",
  todo: "To Do",
  in_progress: "In Progress",
  waiting_on_client: "Waiting on Client",
  review: "Review",
  done: "Done",
  draft: "Draft",
  sent: "Sent",
  overdue: "Overdue",
  partial: "Partial",
  paid: "Paid",
  archived: "Archived",
};
